
version: "3.9"
services:
  incubator-discord:
    build: .
    image: incubator-discord:latest
    env_file: .env
    restart: unless-stopped
    depends_on:
      - mqtt
    networks:
      - bus

  mqtt:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - bus

networks:
  bus: {}